/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labirinth;

import labirinth.view.MainWindow;

public class App {

    public static void main(String[] args) {
        MainWindow window = new MainWindow();
    }
}
